/*

 SAVE_ROOM_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\moon\GitHub\gameboyRPG\res\save_room.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define SaveRoomMapWidth 20
#define SaveRoomMapHeight 18
#define SaveRoomMapBank 0

extern unsigned char SaveRoomMap[];

/* End of SAVE_ROOM_MAP.H */
