/*

 TEST_DUNGEON_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 128 x 128
   Tile set      : test_dungeon.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TestDungeonMapWidth 128
#define TestDungeonMapHeight 128
#define TestDungeonMapBank 0

extern unsigned char TestDungeonMap[];

/* End of TEST_DUNGEON_MAP.H */
